version: '3'

services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
    volumes:
      -  /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/data/postgres:/var/lib/postgresql/data
  sennet-uwsgi:
    image: "sennet/integrated-maps-ui-prod:latest"
    ports:
      - "5001:5001"
    expose:
      - 5001
    volumes:
      - /opt/repositories/vm024-dev/data-products-ui/secret:/opt/secret/
      - /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/data:/opt/data/
      - /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/pipeline_outputs:/opt/pipeline_outputs/
      - /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/media:/opt/media/
  sennet-nginx:
    image: "nginx:alpine"
    volumes:
      - /opt/repositories/vm024-dev/data-products-ui/secret/nginx.conf:/etc/nginx/nginx.conf
      - /opt/repositories/vm024-dev/data-products-ui/secret/data-products-ui.conf:/etc/nginx/conf.d/data-products-ui.conf
      - /etc/pki/nginx:/etc/pki/nginx/
      - /etc/pki/tls:/etc/pki/tls/
      - /opt/repositories/vm024-dev/data-products-ui/media:/opt/media/
      - /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/sennet/static/:/opt/integrated-maps-ui/sennet/static/
    ports:
      - "81:81"
      - "443:4431"
    depends_on:
      - sennet-uwsgi
      - sennet-shinycell2
  sennet-shinycell2:
    image: "shinycell2:latest"
    ports:
      - "3839:3839"
    volumes:
      - /hive/hubmap/data/public/hubmap-data-products/shiny-server:/data
      - /opt/repositories/vm024-dev/data-products-ui/integrated-maps-ui/shiny-server:/srv/shiny-server
    restart: unless-stopped 
