version: '3'

services:
  sennet-db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      -  /opt/data/postgres:/var/lib/postgresql/data
  sennet-uwsgi:
    image: "sennet/integrated-maps-ui-prod:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - /opt/integrated-maps-ui/secret:/opt/integrated-maps-ui/secret/
      - /opt/data:/opt/data/
      - /opt/pipeline_outputs:/opt/pipeline_outputs/
      - /opt/media:/opt/media/
  sennet-nginx:
    image: "nginx:alpine"
    volumes:
      - /opt/integrated-maps-ui/secret/nginx.conf:/etc/nginx/nginx.conf
      - /opt/integrated-maps-ui/secret/integrated-maps-ui.conf:/etc/nginx/conf.d/integrated-maps-ui.conf
      - /etc/pki/nginx:/etc/pki/nginx/
      - /etc/pki/tls:/etc/pki/tls/
      - /opt/media/media:/opt/media/
      - /opt/integrated-maps-ui/sennet/static/:/opt/integrated-maps-ui/sennet/static/
    ports:
      - "80:80"
      - "442:4420"
    depends_on:
      - sennet-uwsgi
      - sennet-shinycell2
  sennet-shinycell2:
    image: "shinycell2:latest"
    ports:
      - "3838:3838"
    volumes:
      - /opt/shiny-server:/data
      - /opt/shiny-server/shiny-server:/srv/shiny-server
    restart: unless-stopped 
